version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: votingdb
      MYSQL_USER: votinguser
      MYSQL_PASSWORD: votingpass
    ports:
      - "3306:3306"
    networks:
      - monitoring-net
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  voting-ui:
    build:
      context: ./frontend
    container_name: voting-ui
    ports:
      - "80:80"
    environment:
      DB_HOST: mysql-db
      DB_NAME: votingdb
      DB_USER: votinguser
      DB_PASS: votingpass
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge
    external: true

